/**
 * generated by Xtext 2.9.0
 */
package ceronsantiago.ui;

import ceronsantiago.ui.AbstractOneSharpExpressiveUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class OneSharpExpressiveUiModule extends AbstractOneSharpExpressiveUiModule {
  public OneSharpExpressiveUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
