/*
 * generated by Xtext 2.9.0
 */
package ceronsantiago.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractOneSharpExpressiveValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(ceronsantiago.oneSharpExpressive.OneSharpExpressivePackage.eINSTANCE);
		return result;
	}
	
}
