/*
 * generated by Xtext 2.9.0
 */
package ceronsantiago.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractOneSharpExpressiveScopeProvider extends DelegatingScopeProvider {
}
