/*
 * generated by Xtext
 */
package org.ceronsantiago;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class OneSharpExpressiveRuntimeModule extends org.ceronsantiago.AbstractOneSharpExpressiveRuntimeModule {

}
