/*
 * generated by Xtext
 */
package org.ceronsantiago;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class OneSharpExpressiveStandaloneSetup extends OneSharpExpressiveStandaloneSetupGenerated{

	public static void doSetup() {
		new OneSharpExpressiveStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

