/**
 * generated by Xtext 2.9.0
 */
package ceronsantiago.oneSharpExpressive.impl;

import ceronsantiago.oneSharpExpressive.IntParamDec;
import ceronsantiago.oneSharpExpressive.OneSharpExpressivePackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Int Param Dec</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class IntParamDecImpl extends ParamDecImpl implements IntParamDec
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected IntParamDecImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return OneSharpExpressivePackage.Literals.INT_PARAM_DEC;
  }

} //IntParamDecImpl
