/**
 * generated by Xtext 2.9.0
 */
package ceronsantiago.oneSharpExpressive.impl;

import ceronsantiago.oneSharpExpressive.*;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class OneSharpExpressiveFactoryImpl extends EFactoryImpl implements OneSharpExpressiveFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static OneSharpExpressiveFactory init()
  {
    try
    {
      OneSharpExpressiveFactory theOneSharpExpressiveFactory = (OneSharpExpressiveFactory)EPackage.Registry.INSTANCE.getEFactory(OneSharpExpressivePackage.eNS_URI);
      if (theOneSharpExpressiveFactory != null)
      {
        return theOneSharpExpressiveFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new OneSharpExpressiveFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public OneSharpExpressiveFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case OneSharpExpressivePackage.PROGRAM: return createProgram();
      case OneSharpExpressivePackage.REGISTER_PARAM: return createRegisterParam();
      case OneSharpExpressivePackage.WORD_PARAM: return createWordParam();
      case OneSharpExpressivePackage.CALL_PARAM: return createCallParam();
      case OneSharpExpressivePackage.WRITE: return createWrite();
      case OneSharpExpressivePackage.NORMAL_CASE: return createNormalCase();
      case OneSharpExpressivePackage.GOTO: return createGoto();
      case OneSharpExpressivePackage.CALL: return createCall();
      case OneSharpExpressivePackage.COMMAND: return createCommand();
      case OneSharpExpressivePackage.UNLABELED_COMMAND: return createUnlabeledCommand();
      case OneSharpExpressivePackage.INT_PARAM_DEC: return createIntParamDec();
      case OneSharpExpressivePackage.STRING_PARAM_DEC: return createStringParamDec();
      case OneSharpExpressivePackage.PARAM_DEC: return createParamDec();
      case OneSharpExpressivePackage.FUNCTION_DECLARATION: return createFunctionDeclaration();
      case OneSharpExpressivePackage.COMMAND_BLOCK: return createCommandBlock();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Program createProgram()
  {
    ProgramImpl program = new ProgramImpl();
    return program;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public RegisterParam createRegisterParam()
  {
    RegisterParamImpl registerParam = new RegisterParamImpl();
    return registerParam;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public WordParam createWordParam()
  {
    WordParamImpl wordParam = new WordParamImpl();
    return wordParam;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public CallParam createCallParam()
  {
    CallParamImpl callParam = new CallParamImpl();
    return callParam;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Write createWrite()
  {
    WriteImpl write = new WriteImpl();
    return write;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NormalCase createNormalCase()
  {
    NormalCaseImpl normalCase = new NormalCaseImpl();
    return normalCase;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Goto createGoto()
  {
    GotoImpl goto_ = new GotoImpl();
    return goto_;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Call createCall()
  {
    CallImpl call = new CallImpl();
    return call;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Command createCommand()
  {
    CommandImpl command = new CommandImpl();
    return command;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public UnlabeledCommand createUnlabeledCommand()
  {
    UnlabeledCommandImpl unlabeledCommand = new UnlabeledCommandImpl();
    return unlabeledCommand;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public IntParamDec createIntParamDec()
  {
    IntParamDecImpl intParamDec = new IntParamDecImpl();
    return intParamDec;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public StringParamDec createStringParamDec()
  {
    StringParamDecImpl stringParamDec = new StringParamDecImpl();
    return stringParamDec;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ParamDec createParamDec()
  {
    ParamDecImpl paramDec = new ParamDecImpl();
    return paramDec;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public FunctionDeclaration createFunctionDeclaration()
  {
    FunctionDeclarationImpl functionDeclaration = new FunctionDeclarationImpl();
    return functionDeclaration;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public CommandBlock createCommandBlock()
  {
    CommandBlockImpl commandBlock = new CommandBlockImpl();
    return commandBlock;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public OneSharpExpressivePackage getOneSharpExpressivePackage()
  {
    return (OneSharpExpressivePackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static OneSharpExpressivePackage getPackage()
  {
    return OneSharpExpressivePackage.eINSTANCE;
  }

} //OneSharpExpressiveFactoryImpl
