/*
 * generated by Xtext 2.9.0
 */
package ceronsantiago.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class OneSharpExpressiveUiModule extends AbstractOneSharpExpressiveUiModule {
}
