/*
 * generated by Xtext 2.9.0
 */
package ceronsantiago.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class OneSharpExpressiveAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("ceronsantiago/parser/antlr/internal/InternalOneSharpExpressive.tokens");
	}
}
