/*
 * generated by Xtext
 */
package org.ceronsantiago.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.ceronsantiago.services.OneSharpExpressiveGrammarAccess;

public class OneSharpExpressiveParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private OneSharpExpressiveGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.ceronsantiago.parser.antlr.internal.InternalOneSharpExpressiveParser createParser(XtextTokenStream stream) {
		return new org.ceronsantiago.parser.antlr.internal.InternalOneSharpExpressiveParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Program";
	}
	
	public OneSharpExpressiveGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(OneSharpExpressiveGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
