/*
 * generated by Xtext
 */
package org.ceronsantiago.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class OneSharpExpressiveAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/ceronsantiago/parser/antlr/internal/InternalOneSharpExpressive.tokens");
	}
}
