/**
 * generated by Xtext 2.9.0
 */
package ceronsantiago.oneSharpExpressive;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Function Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ceronsantiago.oneSharpExpressive.FunctionDeclaration#getName <em>Name</em>}</li>
 *   <li>{@link ceronsantiago.oneSharpExpressive.FunctionDeclaration#getParams <em>Params</em>}</li>
 *   <li>{@link ceronsantiago.oneSharpExpressive.FunctionDeclaration#getBody <em>Body</em>}</li>
 * </ul>
 *
 * @see ceronsantiago.oneSharpExpressive.OneSharpExpressivePackage#getFunctionDeclaration()
 * @model
 * @generated
 */
public interface FunctionDeclaration extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see ceronsantiago.oneSharpExpressive.OneSharpExpressivePackage#getFunctionDeclaration_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link ceronsantiago.oneSharpExpressive.FunctionDeclaration#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Params</b></em>' containment reference list.
   * The list contents are of type {@link ceronsantiago.oneSharpExpressive.ParamDec}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Params</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Params</em>' containment reference list.
   * @see ceronsantiago.oneSharpExpressive.OneSharpExpressivePackage#getFunctionDeclaration_Params()
   * @model containment="true"
   * @generated
   */
  EList<ParamDec> getParams();

  /**
   * Returns the value of the '<em><b>Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Body</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Body</em>' containment reference.
   * @see #setBody(CommandBlock)
   * @see ceronsantiago.oneSharpExpressive.OneSharpExpressivePackage#getFunctionDeclaration_Body()
   * @model containment="true"
   * @generated
   */
  CommandBlock getBody();

  /**
   * Sets the value of the '{@link ceronsantiago.oneSharpExpressive.FunctionDeclaration#getBody <em>Body</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Body</em>' containment reference.
   * @see #getBody()
   * @generated
   */
  void setBody(CommandBlock value);

} // FunctionDeclaration
