/**
 * generated by Xtext 2.9.0
 */
package ceronsantiago.oneSharpExpressive;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Goto</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ceronsantiago.oneSharpExpressive.Goto#getLabel <em>Label</em>}</li>
 * </ul>
 *
 * @see ceronsantiago.oneSharpExpressive.OneSharpExpressivePackage#getGoto()
 * @model
 * @generated
 */
public interface Goto extends UnlabeledCommand
{
  /**
   * Returns the value of the '<em><b>Label</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Label</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Label</em>' reference.
   * @see #setLabel(Command)
   * @see ceronsantiago.oneSharpExpressive.OneSharpExpressivePackage#getGoto_Label()
   * @model
   * @generated
   */
  Command getLabel();

  /**
   * Sets the value of the '{@link ceronsantiago.oneSharpExpressive.Goto#getLabel <em>Label</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Label</em>' reference.
   * @see #getLabel()
   * @generated
   */
  void setLabel(Command value);

} // Goto
