/**
 * generated by Xtext 2.9.0
 */
package ceronsantiago.oneSharpExpressive;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Normal Case</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ceronsantiago.oneSharpExpressive.NormalCase#getRegister <em>Register</em>}</li>
 *   <li>{@link ceronsantiago.oneSharpExpressive.NormalCase#getCaseEmpty <em>Case Empty</em>}</li>
 *   <li>{@link ceronsantiago.oneSharpExpressive.NormalCase#getCaseOne <em>Case One</em>}</li>
 *   <li>{@link ceronsantiago.oneSharpExpressive.NormalCase#getCaseSharp <em>Case Sharp</em>}</li>
 * </ul>
 *
 * @see ceronsantiago.oneSharpExpressive.OneSharpExpressivePackage#getNormalCase()
 * @model
 * @generated
 */
public interface NormalCase extends UnlabeledCommand
{
  /**
   * Returns the value of the '<em><b>Register</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Register</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Register</em>' containment reference.
   * @see #setRegister(RegisterParam)
   * @see ceronsantiago.oneSharpExpressive.OneSharpExpressivePackage#getNormalCase_Register()
   * @model containment="true"
   * @generated
   */
  RegisterParam getRegister();

  /**
   * Sets the value of the '{@link ceronsantiago.oneSharpExpressive.NormalCase#getRegister <em>Register</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Register</em>' containment reference.
   * @see #getRegister()
   * @generated
   */
  void setRegister(RegisterParam value);

  /**
   * Returns the value of the '<em><b>Case Empty</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Case Empty</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Case Empty</em>' containment reference.
   * @see #setCaseEmpty(CommandBlock)
   * @see ceronsantiago.oneSharpExpressive.OneSharpExpressivePackage#getNormalCase_CaseEmpty()
   * @model containment="true"
   * @generated
   */
  CommandBlock getCaseEmpty();

  /**
   * Sets the value of the '{@link ceronsantiago.oneSharpExpressive.NormalCase#getCaseEmpty <em>Case Empty</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Case Empty</em>' containment reference.
   * @see #getCaseEmpty()
   * @generated
   */
  void setCaseEmpty(CommandBlock value);

  /**
   * Returns the value of the '<em><b>Case One</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Case One</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Case One</em>' containment reference.
   * @see #setCaseOne(CommandBlock)
   * @see ceronsantiago.oneSharpExpressive.OneSharpExpressivePackage#getNormalCase_CaseOne()
   * @model containment="true"
   * @generated
   */
  CommandBlock getCaseOne();

  /**
   * Sets the value of the '{@link ceronsantiago.oneSharpExpressive.NormalCase#getCaseOne <em>Case One</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Case One</em>' containment reference.
   * @see #getCaseOne()
   * @generated
   */
  void setCaseOne(CommandBlock value);

  /**
   * Returns the value of the '<em><b>Case Sharp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Case Sharp</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Case Sharp</em>' containment reference.
   * @see #setCaseSharp(CommandBlock)
   * @see ceronsantiago.oneSharpExpressive.OneSharpExpressivePackage#getNormalCase_CaseSharp()
   * @model containment="true"
   * @generated
   */
  CommandBlock getCaseSharp();

  /**
   * Sets the value of the '{@link ceronsantiago.oneSharpExpressive.NormalCase#getCaseSharp <em>Case Sharp</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Case Sharp</em>' containment reference.
   * @see #getCaseSharp()
   * @generated
   */
  void setCaseSharp(CommandBlock value);

} // NormalCase
