/**
 * generated by Xtext 2.9.0
 */
package ceronsantiago.oneSharpExpressive;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see ceronsantiago.oneSharpExpressive.OneSharpExpressiveFactory
 * @model kind="package"
 * @generated
 */
public interface OneSharpExpressivePackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "oneSharpExpressive";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.ceronsantiago.org/OneSharpExpressive";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "oneSharpExpressive";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  OneSharpExpressivePackage eINSTANCE = ceronsantiago.oneSharpExpressive.impl.OneSharpExpressivePackageImpl.init();

  /**
   * The meta object id for the '{@link ceronsantiago.oneSharpExpressive.impl.ProgramImpl <em>Program</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ceronsantiago.oneSharpExpressive.impl.ProgramImpl
   * @see ceronsantiago.oneSharpExpressive.impl.OneSharpExpressivePackageImpl#getProgram()
   * @generated
   */
  int PROGRAM = 0;

  /**
   * The feature id for the '<em><b>Functions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM__FUNCTIONS = 0;

  /**
   * The feature id for the '<em><b>Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM__BODY = 1;

  /**
   * The number of structural features of the '<em>Program</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link ceronsantiago.oneSharpExpressive.impl.RegisterParamImpl <em>Register Param</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ceronsantiago.oneSharpExpressive.impl.RegisterParamImpl
   * @see ceronsantiago.oneSharpExpressive.impl.OneSharpExpressivePackageImpl#getRegisterParam()
   * @generated
   */
  int REGISTER_PARAM = 1;

  /**
   * The feature id for the '<em><b>Param</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REGISTER_PARAM__PARAM = 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REGISTER_PARAM__VALUE = 1;

  /**
   * The number of structural features of the '<em>Register Param</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REGISTER_PARAM_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link ceronsantiago.oneSharpExpressive.impl.WordParamImpl <em>Word Param</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ceronsantiago.oneSharpExpressive.impl.WordParamImpl
   * @see ceronsantiago.oneSharpExpressive.impl.OneSharpExpressivePackageImpl#getWordParam()
   * @generated
   */
  int WORD_PARAM = 2;

  /**
   * The feature id for the '<em><b>Param</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WORD_PARAM__PARAM = 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WORD_PARAM__VALUE = 1;

  /**
   * The number of structural features of the '<em>Word Param</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WORD_PARAM_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link ceronsantiago.oneSharpExpressive.impl.CallParamImpl <em>Call Param</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ceronsantiago.oneSharpExpressive.impl.CallParamImpl
   * @see ceronsantiago.oneSharpExpressive.impl.OneSharpExpressivePackageImpl#getCallParam()
   * @generated
   */
  int CALL_PARAM = 3;

  /**
   * The feature id for the '<em><b>Int Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CALL_PARAM__INT_VAL = 0;

  /**
   * The feature id for the '<em><b>String Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CALL_PARAM__STRING_VAL = 1;

  /**
   * The feature id for the '<em><b>Param</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CALL_PARAM__PARAM = 2;

  /**
   * The number of structural features of the '<em>Call Param</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CALL_PARAM_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link ceronsantiago.oneSharpExpressive.impl.UnlabeledCommandImpl <em>Unlabeled Command</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ceronsantiago.oneSharpExpressive.impl.UnlabeledCommandImpl
   * @see ceronsantiago.oneSharpExpressive.impl.OneSharpExpressivePackageImpl#getUnlabeledCommand()
   * @generated
   */
  int UNLABELED_COMMAND = 9;

  /**
   * The number of structural features of the '<em>Unlabeled Command</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNLABELED_COMMAND_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link ceronsantiago.oneSharpExpressive.impl.WriteImpl <em>Write</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ceronsantiago.oneSharpExpressive.impl.WriteImpl
   * @see ceronsantiago.oneSharpExpressive.impl.OneSharpExpressivePackageImpl#getWrite()
   * @generated
   */
  int WRITE = 4;

  /**
   * The feature id for the '<em><b>Register</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WRITE__REGISTER = UNLABELED_COMMAND_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Word</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WRITE__WORD = UNLABELED_COMMAND_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Write</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WRITE_FEATURE_COUNT = UNLABELED_COMMAND_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link ceronsantiago.oneSharpExpressive.impl.NormalCaseImpl <em>Normal Case</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ceronsantiago.oneSharpExpressive.impl.NormalCaseImpl
   * @see ceronsantiago.oneSharpExpressive.impl.OneSharpExpressivePackageImpl#getNormalCase()
   * @generated
   */
  int NORMAL_CASE = 5;

  /**
   * The feature id for the '<em><b>Register</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NORMAL_CASE__REGISTER = UNLABELED_COMMAND_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Case Empty</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NORMAL_CASE__CASE_EMPTY = UNLABELED_COMMAND_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Case One</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NORMAL_CASE__CASE_ONE = UNLABELED_COMMAND_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Case Sharp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NORMAL_CASE__CASE_SHARP = UNLABELED_COMMAND_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>Normal Case</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NORMAL_CASE_FEATURE_COUNT = UNLABELED_COMMAND_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link ceronsantiago.oneSharpExpressive.impl.GotoImpl <em>Goto</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ceronsantiago.oneSharpExpressive.impl.GotoImpl
   * @see ceronsantiago.oneSharpExpressive.impl.OneSharpExpressivePackageImpl#getGoto()
   * @generated
   */
  int GOTO = 6;

  /**
   * The feature id for the '<em><b>Label</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GOTO__LABEL = UNLABELED_COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Goto</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GOTO_FEATURE_COUNT = UNLABELED_COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link ceronsantiago.oneSharpExpressive.impl.CallImpl <em>Call</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ceronsantiago.oneSharpExpressive.impl.CallImpl
   * @see ceronsantiago.oneSharpExpressive.impl.OneSharpExpressivePackageImpl#getCall()
   * @generated
   */
  int CALL = 7;

  /**
   * The feature id for the '<em><b>Function</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CALL__FUNCTION = UNLABELED_COMMAND_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Params</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CALL__PARAMS = UNLABELED_COMMAND_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Call</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CALL_FEATURE_COUNT = UNLABELED_COMMAND_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link ceronsantiago.oneSharpExpressive.impl.CommandImpl <em>Command</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ceronsantiago.oneSharpExpressive.impl.CommandImpl
   * @see ceronsantiago.oneSharpExpressive.impl.OneSharpExpressivePackageImpl#getCommand()
   * @generated
   */
  int COMMAND = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND__NAME = 0;

  /**
   * The feature id for the '<em><b>Command</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND__COMMAND = 1;

  /**
   * The number of structural features of the '<em>Command</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link ceronsantiago.oneSharpExpressive.impl.ParamDecImpl <em>Param Dec</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ceronsantiago.oneSharpExpressive.impl.ParamDecImpl
   * @see ceronsantiago.oneSharpExpressive.impl.OneSharpExpressivePackageImpl#getParamDec()
   * @generated
   */
  int PARAM_DEC = 12;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAM_DEC__NAME = 0;

  /**
   * The number of structural features of the '<em>Param Dec</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAM_DEC_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link ceronsantiago.oneSharpExpressive.impl.IntParamDecImpl <em>Int Param Dec</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ceronsantiago.oneSharpExpressive.impl.IntParamDecImpl
   * @see ceronsantiago.oneSharpExpressive.impl.OneSharpExpressivePackageImpl#getIntParamDec()
   * @generated
   */
  int INT_PARAM_DEC = 10;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_PARAM_DEC__NAME = PARAM_DEC__NAME;

  /**
   * The number of structural features of the '<em>Int Param Dec</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_PARAM_DEC_FEATURE_COUNT = PARAM_DEC_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link ceronsantiago.oneSharpExpressive.impl.StringParamDecImpl <em>String Param Dec</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ceronsantiago.oneSharpExpressive.impl.StringParamDecImpl
   * @see ceronsantiago.oneSharpExpressive.impl.OneSharpExpressivePackageImpl#getStringParamDec()
   * @generated
   */
  int STRING_PARAM_DEC = 11;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_PARAM_DEC__NAME = PARAM_DEC__NAME;

  /**
   * The number of structural features of the '<em>String Param Dec</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_PARAM_DEC_FEATURE_COUNT = PARAM_DEC_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link ceronsantiago.oneSharpExpressive.impl.FunctionDeclarationImpl <em>Function Declaration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ceronsantiago.oneSharpExpressive.impl.FunctionDeclarationImpl
   * @see ceronsantiago.oneSharpExpressive.impl.OneSharpExpressivePackageImpl#getFunctionDeclaration()
   * @generated
   */
  int FUNCTION_DECLARATION = 13;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_DECLARATION__NAME = 0;

  /**
   * The feature id for the '<em><b>Params</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_DECLARATION__PARAMS = 1;

  /**
   * The feature id for the '<em><b>Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_DECLARATION__BODY = 2;

  /**
   * The number of structural features of the '<em>Function Declaration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_DECLARATION_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link ceronsantiago.oneSharpExpressive.impl.CommandBlockImpl <em>Command Block</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ceronsantiago.oneSharpExpressive.impl.CommandBlockImpl
   * @see ceronsantiago.oneSharpExpressive.impl.OneSharpExpressivePackageImpl#getCommandBlock()
   * @generated
   */
  int COMMAND_BLOCK = 14;

  /**
   * The feature id for the '<em><b>Commands</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND_BLOCK__COMMANDS = 0;

  /**
   * The number of structural features of the '<em>Command Block</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND_BLOCK_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link ceronsantiago.oneSharpExpressive.Program <em>Program</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Program</em>'.
   * @see ceronsantiago.oneSharpExpressive.Program
   * @generated
   */
  EClass getProgram();

  /**
   * Returns the meta object for the containment reference list '{@link ceronsantiago.oneSharpExpressive.Program#getFunctions <em>Functions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Functions</em>'.
   * @see ceronsantiago.oneSharpExpressive.Program#getFunctions()
   * @see #getProgram()
   * @generated
   */
  EReference getProgram_Functions();

  /**
   * Returns the meta object for the containment reference '{@link ceronsantiago.oneSharpExpressive.Program#getBody <em>Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Body</em>'.
   * @see ceronsantiago.oneSharpExpressive.Program#getBody()
   * @see #getProgram()
   * @generated
   */
  EReference getProgram_Body();

  /**
   * Returns the meta object for class '{@link ceronsantiago.oneSharpExpressive.RegisterParam <em>Register Param</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Register Param</em>'.
   * @see ceronsantiago.oneSharpExpressive.RegisterParam
   * @generated
   */
  EClass getRegisterParam();

  /**
   * Returns the meta object for the reference '{@link ceronsantiago.oneSharpExpressive.RegisterParam#getParam <em>Param</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Param</em>'.
   * @see ceronsantiago.oneSharpExpressive.RegisterParam#getParam()
   * @see #getRegisterParam()
   * @generated
   */
  EReference getRegisterParam_Param();

  /**
   * Returns the meta object for the attribute '{@link ceronsantiago.oneSharpExpressive.RegisterParam#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see ceronsantiago.oneSharpExpressive.RegisterParam#getValue()
   * @see #getRegisterParam()
   * @generated
   */
  EAttribute getRegisterParam_Value();

  /**
   * Returns the meta object for class '{@link ceronsantiago.oneSharpExpressive.WordParam <em>Word Param</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Word Param</em>'.
   * @see ceronsantiago.oneSharpExpressive.WordParam
   * @generated
   */
  EClass getWordParam();

  /**
   * Returns the meta object for the reference '{@link ceronsantiago.oneSharpExpressive.WordParam#getParam <em>Param</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Param</em>'.
   * @see ceronsantiago.oneSharpExpressive.WordParam#getParam()
   * @see #getWordParam()
   * @generated
   */
  EReference getWordParam_Param();

  /**
   * Returns the meta object for the attribute '{@link ceronsantiago.oneSharpExpressive.WordParam#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see ceronsantiago.oneSharpExpressive.WordParam#getValue()
   * @see #getWordParam()
   * @generated
   */
  EAttribute getWordParam_Value();

  /**
   * Returns the meta object for class '{@link ceronsantiago.oneSharpExpressive.CallParam <em>Call Param</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Call Param</em>'.
   * @see ceronsantiago.oneSharpExpressive.CallParam
   * @generated
   */
  EClass getCallParam();

  /**
   * Returns the meta object for the attribute '{@link ceronsantiago.oneSharpExpressive.CallParam#getIntVal <em>Int Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Int Val</em>'.
   * @see ceronsantiago.oneSharpExpressive.CallParam#getIntVal()
   * @see #getCallParam()
   * @generated
   */
  EAttribute getCallParam_IntVal();

  /**
   * Returns the meta object for the attribute '{@link ceronsantiago.oneSharpExpressive.CallParam#getStringVal <em>String Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>String Val</em>'.
   * @see ceronsantiago.oneSharpExpressive.CallParam#getStringVal()
   * @see #getCallParam()
   * @generated
   */
  EAttribute getCallParam_StringVal();

  /**
   * Returns the meta object for the reference '{@link ceronsantiago.oneSharpExpressive.CallParam#getParam <em>Param</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Param</em>'.
   * @see ceronsantiago.oneSharpExpressive.CallParam#getParam()
   * @see #getCallParam()
   * @generated
   */
  EReference getCallParam_Param();

  /**
   * Returns the meta object for class '{@link ceronsantiago.oneSharpExpressive.Write <em>Write</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Write</em>'.
   * @see ceronsantiago.oneSharpExpressive.Write
   * @generated
   */
  EClass getWrite();

  /**
   * Returns the meta object for the containment reference '{@link ceronsantiago.oneSharpExpressive.Write#getRegister <em>Register</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Register</em>'.
   * @see ceronsantiago.oneSharpExpressive.Write#getRegister()
   * @see #getWrite()
   * @generated
   */
  EReference getWrite_Register();

  /**
   * Returns the meta object for the containment reference '{@link ceronsantiago.oneSharpExpressive.Write#getWord <em>Word</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Word</em>'.
   * @see ceronsantiago.oneSharpExpressive.Write#getWord()
   * @see #getWrite()
   * @generated
   */
  EReference getWrite_Word();

  /**
   * Returns the meta object for class '{@link ceronsantiago.oneSharpExpressive.NormalCase <em>Normal Case</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Normal Case</em>'.
   * @see ceronsantiago.oneSharpExpressive.NormalCase
   * @generated
   */
  EClass getNormalCase();

  /**
   * Returns the meta object for the containment reference '{@link ceronsantiago.oneSharpExpressive.NormalCase#getRegister <em>Register</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Register</em>'.
   * @see ceronsantiago.oneSharpExpressive.NormalCase#getRegister()
   * @see #getNormalCase()
   * @generated
   */
  EReference getNormalCase_Register();

  /**
   * Returns the meta object for the containment reference '{@link ceronsantiago.oneSharpExpressive.NormalCase#getCaseEmpty <em>Case Empty</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Case Empty</em>'.
   * @see ceronsantiago.oneSharpExpressive.NormalCase#getCaseEmpty()
   * @see #getNormalCase()
   * @generated
   */
  EReference getNormalCase_CaseEmpty();

  /**
   * Returns the meta object for the containment reference '{@link ceronsantiago.oneSharpExpressive.NormalCase#getCaseOne <em>Case One</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Case One</em>'.
   * @see ceronsantiago.oneSharpExpressive.NormalCase#getCaseOne()
   * @see #getNormalCase()
   * @generated
   */
  EReference getNormalCase_CaseOne();

  /**
   * Returns the meta object for the containment reference '{@link ceronsantiago.oneSharpExpressive.NormalCase#getCaseSharp <em>Case Sharp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Case Sharp</em>'.
   * @see ceronsantiago.oneSharpExpressive.NormalCase#getCaseSharp()
   * @see #getNormalCase()
   * @generated
   */
  EReference getNormalCase_CaseSharp();

  /**
   * Returns the meta object for class '{@link ceronsantiago.oneSharpExpressive.Goto <em>Goto</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Goto</em>'.
   * @see ceronsantiago.oneSharpExpressive.Goto
   * @generated
   */
  EClass getGoto();

  /**
   * Returns the meta object for the reference '{@link ceronsantiago.oneSharpExpressive.Goto#getLabel <em>Label</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Label</em>'.
   * @see ceronsantiago.oneSharpExpressive.Goto#getLabel()
   * @see #getGoto()
   * @generated
   */
  EReference getGoto_Label();

  /**
   * Returns the meta object for class '{@link ceronsantiago.oneSharpExpressive.Call <em>Call</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Call</em>'.
   * @see ceronsantiago.oneSharpExpressive.Call
   * @generated
   */
  EClass getCall();

  /**
   * Returns the meta object for the reference '{@link ceronsantiago.oneSharpExpressive.Call#getFunction <em>Function</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Function</em>'.
   * @see ceronsantiago.oneSharpExpressive.Call#getFunction()
   * @see #getCall()
   * @generated
   */
  EReference getCall_Function();

  /**
   * Returns the meta object for the containment reference list '{@link ceronsantiago.oneSharpExpressive.Call#getParams <em>Params</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Params</em>'.
   * @see ceronsantiago.oneSharpExpressive.Call#getParams()
   * @see #getCall()
   * @generated
   */
  EReference getCall_Params();

  /**
   * Returns the meta object for class '{@link ceronsantiago.oneSharpExpressive.Command <em>Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Command</em>'.
   * @see ceronsantiago.oneSharpExpressive.Command
   * @generated
   */
  EClass getCommand();

  /**
   * Returns the meta object for the attribute '{@link ceronsantiago.oneSharpExpressive.Command#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see ceronsantiago.oneSharpExpressive.Command#getName()
   * @see #getCommand()
   * @generated
   */
  EAttribute getCommand_Name();

  /**
   * Returns the meta object for the containment reference '{@link ceronsantiago.oneSharpExpressive.Command#getCommand <em>Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Command</em>'.
   * @see ceronsantiago.oneSharpExpressive.Command#getCommand()
   * @see #getCommand()
   * @generated
   */
  EReference getCommand_Command();

  /**
   * Returns the meta object for class '{@link ceronsantiago.oneSharpExpressive.UnlabeledCommand <em>Unlabeled Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Unlabeled Command</em>'.
   * @see ceronsantiago.oneSharpExpressive.UnlabeledCommand
   * @generated
   */
  EClass getUnlabeledCommand();

  /**
   * Returns the meta object for class '{@link ceronsantiago.oneSharpExpressive.IntParamDec <em>Int Param Dec</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Int Param Dec</em>'.
   * @see ceronsantiago.oneSharpExpressive.IntParamDec
   * @generated
   */
  EClass getIntParamDec();

  /**
   * Returns the meta object for class '{@link ceronsantiago.oneSharpExpressive.StringParamDec <em>String Param Dec</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>String Param Dec</em>'.
   * @see ceronsantiago.oneSharpExpressive.StringParamDec
   * @generated
   */
  EClass getStringParamDec();

  /**
   * Returns the meta object for class '{@link ceronsantiago.oneSharpExpressive.ParamDec <em>Param Dec</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Param Dec</em>'.
   * @see ceronsantiago.oneSharpExpressive.ParamDec
   * @generated
   */
  EClass getParamDec();

  /**
   * Returns the meta object for the attribute '{@link ceronsantiago.oneSharpExpressive.ParamDec#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see ceronsantiago.oneSharpExpressive.ParamDec#getName()
   * @see #getParamDec()
   * @generated
   */
  EAttribute getParamDec_Name();

  /**
   * Returns the meta object for class '{@link ceronsantiago.oneSharpExpressive.FunctionDeclaration <em>Function Declaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Function Declaration</em>'.
   * @see ceronsantiago.oneSharpExpressive.FunctionDeclaration
   * @generated
   */
  EClass getFunctionDeclaration();

  /**
   * Returns the meta object for the attribute '{@link ceronsantiago.oneSharpExpressive.FunctionDeclaration#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see ceronsantiago.oneSharpExpressive.FunctionDeclaration#getName()
   * @see #getFunctionDeclaration()
   * @generated
   */
  EAttribute getFunctionDeclaration_Name();

  /**
   * Returns the meta object for the containment reference list '{@link ceronsantiago.oneSharpExpressive.FunctionDeclaration#getParams <em>Params</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Params</em>'.
   * @see ceronsantiago.oneSharpExpressive.FunctionDeclaration#getParams()
   * @see #getFunctionDeclaration()
   * @generated
   */
  EReference getFunctionDeclaration_Params();

  /**
   * Returns the meta object for the containment reference '{@link ceronsantiago.oneSharpExpressive.FunctionDeclaration#getBody <em>Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Body</em>'.
   * @see ceronsantiago.oneSharpExpressive.FunctionDeclaration#getBody()
   * @see #getFunctionDeclaration()
   * @generated
   */
  EReference getFunctionDeclaration_Body();

  /**
   * Returns the meta object for class '{@link ceronsantiago.oneSharpExpressive.CommandBlock <em>Command Block</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Command Block</em>'.
   * @see ceronsantiago.oneSharpExpressive.CommandBlock
   * @generated
   */
  EClass getCommandBlock();

  /**
   * Returns the meta object for the containment reference list '{@link ceronsantiago.oneSharpExpressive.CommandBlock#getCommands <em>Commands</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Commands</em>'.
   * @see ceronsantiago.oneSharpExpressive.CommandBlock#getCommands()
   * @see #getCommandBlock()
   * @generated
   */
  EReference getCommandBlock_Commands();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  OneSharpExpressiveFactory getOneSharpExpressiveFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link ceronsantiago.oneSharpExpressive.impl.ProgramImpl <em>Program</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ceronsantiago.oneSharpExpressive.impl.ProgramImpl
     * @see ceronsantiago.oneSharpExpressive.impl.OneSharpExpressivePackageImpl#getProgram()
     * @generated
     */
    EClass PROGRAM = eINSTANCE.getProgram();

    /**
     * The meta object literal for the '<em><b>Functions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROGRAM__FUNCTIONS = eINSTANCE.getProgram_Functions();

    /**
     * The meta object literal for the '<em><b>Body</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROGRAM__BODY = eINSTANCE.getProgram_Body();

    /**
     * The meta object literal for the '{@link ceronsantiago.oneSharpExpressive.impl.RegisterParamImpl <em>Register Param</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ceronsantiago.oneSharpExpressive.impl.RegisterParamImpl
     * @see ceronsantiago.oneSharpExpressive.impl.OneSharpExpressivePackageImpl#getRegisterParam()
     * @generated
     */
    EClass REGISTER_PARAM = eINSTANCE.getRegisterParam();

    /**
     * The meta object literal for the '<em><b>Param</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REGISTER_PARAM__PARAM = eINSTANCE.getRegisterParam_Param();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REGISTER_PARAM__VALUE = eINSTANCE.getRegisterParam_Value();

    /**
     * The meta object literal for the '{@link ceronsantiago.oneSharpExpressive.impl.WordParamImpl <em>Word Param</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ceronsantiago.oneSharpExpressive.impl.WordParamImpl
     * @see ceronsantiago.oneSharpExpressive.impl.OneSharpExpressivePackageImpl#getWordParam()
     * @generated
     */
    EClass WORD_PARAM = eINSTANCE.getWordParam();

    /**
     * The meta object literal for the '<em><b>Param</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WORD_PARAM__PARAM = eINSTANCE.getWordParam_Param();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WORD_PARAM__VALUE = eINSTANCE.getWordParam_Value();

    /**
     * The meta object literal for the '{@link ceronsantiago.oneSharpExpressive.impl.CallParamImpl <em>Call Param</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ceronsantiago.oneSharpExpressive.impl.CallParamImpl
     * @see ceronsantiago.oneSharpExpressive.impl.OneSharpExpressivePackageImpl#getCallParam()
     * @generated
     */
    EClass CALL_PARAM = eINSTANCE.getCallParam();

    /**
     * The meta object literal for the '<em><b>Int Val</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CALL_PARAM__INT_VAL = eINSTANCE.getCallParam_IntVal();

    /**
     * The meta object literal for the '<em><b>String Val</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CALL_PARAM__STRING_VAL = eINSTANCE.getCallParam_StringVal();

    /**
     * The meta object literal for the '<em><b>Param</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CALL_PARAM__PARAM = eINSTANCE.getCallParam_Param();

    /**
     * The meta object literal for the '{@link ceronsantiago.oneSharpExpressive.impl.WriteImpl <em>Write</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ceronsantiago.oneSharpExpressive.impl.WriteImpl
     * @see ceronsantiago.oneSharpExpressive.impl.OneSharpExpressivePackageImpl#getWrite()
     * @generated
     */
    EClass WRITE = eINSTANCE.getWrite();

    /**
     * The meta object literal for the '<em><b>Register</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WRITE__REGISTER = eINSTANCE.getWrite_Register();

    /**
     * The meta object literal for the '<em><b>Word</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WRITE__WORD = eINSTANCE.getWrite_Word();

    /**
     * The meta object literal for the '{@link ceronsantiago.oneSharpExpressive.impl.NormalCaseImpl <em>Normal Case</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ceronsantiago.oneSharpExpressive.impl.NormalCaseImpl
     * @see ceronsantiago.oneSharpExpressive.impl.OneSharpExpressivePackageImpl#getNormalCase()
     * @generated
     */
    EClass NORMAL_CASE = eINSTANCE.getNormalCase();

    /**
     * The meta object literal for the '<em><b>Register</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NORMAL_CASE__REGISTER = eINSTANCE.getNormalCase_Register();

    /**
     * The meta object literal for the '<em><b>Case Empty</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NORMAL_CASE__CASE_EMPTY = eINSTANCE.getNormalCase_CaseEmpty();

    /**
     * The meta object literal for the '<em><b>Case One</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NORMAL_CASE__CASE_ONE = eINSTANCE.getNormalCase_CaseOne();

    /**
     * The meta object literal for the '<em><b>Case Sharp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NORMAL_CASE__CASE_SHARP = eINSTANCE.getNormalCase_CaseSharp();

    /**
     * The meta object literal for the '{@link ceronsantiago.oneSharpExpressive.impl.GotoImpl <em>Goto</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ceronsantiago.oneSharpExpressive.impl.GotoImpl
     * @see ceronsantiago.oneSharpExpressive.impl.OneSharpExpressivePackageImpl#getGoto()
     * @generated
     */
    EClass GOTO = eINSTANCE.getGoto();

    /**
     * The meta object literal for the '<em><b>Label</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GOTO__LABEL = eINSTANCE.getGoto_Label();

    /**
     * The meta object literal for the '{@link ceronsantiago.oneSharpExpressive.impl.CallImpl <em>Call</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ceronsantiago.oneSharpExpressive.impl.CallImpl
     * @see ceronsantiago.oneSharpExpressive.impl.OneSharpExpressivePackageImpl#getCall()
     * @generated
     */
    EClass CALL = eINSTANCE.getCall();

    /**
     * The meta object literal for the '<em><b>Function</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CALL__FUNCTION = eINSTANCE.getCall_Function();

    /**
     * The meta object literal for the '<em><b>Params</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CALL__PARAMS = eINSTANCE.getCall_Params();

    /**
     * The meta object literal for the '{@link ceronsantiago.oneSharpExpressive.impl.CommandImpl <em>Command</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ceronsantiago.oneSharpExpressive.impl.CommandImpl
     * @see ceronsantiago.oneSharpExpressive.impl.OneSharpExpressivePackageImpl#getCommand()
     * @generated
     */
    EClass COMMAND = eINSTANCE.getCommand();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMMAND__NAME = eINSTANCE.getCommand_Name();

    /**
     * The meta object literal for the '<em><b>Command</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMMAND__COMMAND = eINSTANCE.getCommand_Command();

    /**
     * The meta object literal for the '{@link ceronsantiago.oneSharpExpressive.impl.UnlabeledCommandImpl <em>Unlabeled Command</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ceronsantiago.oneSharpExpressive.impl.UnlabeledCommandImpl
     * @see ceronsantiago.oneSharpExpressive.impl.OneSharpExpressivePackageImpl#getUnlabeledCommand()
     * @generated
     */
    EClass UNLABELED_COMMAND = eINSTANCE.getUnlabeledCommand();

    /**
     * The meta object literal for the '{@link ceronsantiago.oneSharpExpressive.impl.IntParamDecImpl <em>Int Param Dec</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ceronsantiago.oneSharpExpressive.impl.IntParamDecImpl
     * @see ceronsantiago.oneSharpExpressive.impl.OneSharpExpressivePackageImpl#getIntParamDec()
     * @generated
     */
    EClass INT_PARAM_DEC = eINSTANCE.getIntParamDec();

    /**
     * The meta object literal for the '{@link ceronsantiago.oneSharpExpressive.impl.StringParamDecImpl <em>String Param Dec</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ceronsantiago.oneSharpExpressive.impl.StringParamDecImpl
     * @see ceronsantiago.oneSharpExpressive.impl.OneSharpExpressivePackageImpl#getStringParamDec()
     * @generated
     */
    EClass STRING_PARAM_DEC = eINSTANCE.getStringParamDec();

    /**
     * The meta object literal for the '{@link ceronsantiago.oneSharpExpressive.impl.ParamDecImpl <em>Param Dec</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ceronsantiago.oneSharpExpressive.impl.ParamDecImpl
     * @see ceronsantiago.oneSharpExpressive.impl.OneSharpExpressivePackageImpl#getParamDec()
     * @generated
     */
    EClass PARAM_DEC = eINSTANCE.getParamDec();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAM_DEC__NAME = eINSTANCE.getParamDec_Name();

    /**
     * The meta object literal for the '{@link ceronsantiago.oneSharpExpressive.impl.FunctionDeclarationImpl <em>Function Declaration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ceronsantiago.oneSharpExpressive.impl.FunctionDeclarationImpl
     * @see ceronsantiago.oneSharpExpressive.impl.OneSharpExpressivePackageImpl#getFunctionDeclaration()
     * @generated
     */
    EClass FUNCTION_DECLARATION = eINSTANCE.getFunctionDeclaration();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FUNCTION_DECLARATION__NAME = eINSTANCE.getFunctionDeclaration_Name();

    /**
     * The meta object literal for the '<em><b>Params</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUNCTION_DECLARATION__PARAMS = eINSTANCE.getFunctionDeclaration_Params();

    /**
     * The meta object literal for the '<em><b>Body</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUNCTION_DECLARATION__BODY = eINSTANCE.getFunctionDeclaration_Body();

    /**
     * The meta object literal for the '{@link ceronsantiago.oneSharpExpressive.impl.CommandBlockImpl <em>Command Block</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ceronsantiago.oneSharpExpressive.impl.CommandBlockImpl
     * @see ceronsantiago.oneSharpExpressive.impl.OneSharpExpressivePackageImpl#getCommandBlock()
     * @generated
     */
    EClass COMMAND_BLOCK = eINSTANCE.getCommandBlock();

    /**
     * The meta object literal for the '<em><b>Commands</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMMAND_BLOCK__COMMANDS = eINSTANCE.getCommandBlock_Commands();

  }

} //OneSharpExpressivePackage
