/**
 * generated by Xtext 2.9.0
 */
package ceronsantiago.oneSharpExpressive;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>String Param Dec</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see ceronsantiago.oneSharpExpressive.OneSharpExpressivePackage#getStringParamDec()
 * @model
 * @generated
 */
public interface StringParamDec extends ParamDec
{
} // StringParamDec
