/**
 * generated by Xtext 2.9.0
 */
package ceronsantiago.oneSharpExpressive;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Unlabeled Command</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see ceronsantiago.oneSharpExpressive.OneSharpExpressivePackage#getUnlabeledCommand()
 * @model
 * @generated
 */
public interface UnlabeledCommand extends EObject
{
} // UnlabeledCommand
