/**
 * generated by Xtext 2.9.0
 */
package ceronsantiago.oneSharpExpressive;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Write</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ceronsantiago.oneSharpExpressive.Write#getRegister <em>Register</em>}</li>
 *   <li>{@link ceronsantiago.oneSharpExpressive.Write#getWord <em>Word</em>}</li>
 * </ul>
 *
 * @see ceronsantiago.oneSharpExpressive.OneSharpExpressivePackage#getWrite()
 * @model
 * @generated
 */
public interface Write extends UnlabeledCommand
{
  /**
   * Returns the value of the '<em><b>Register</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Register</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Register</em>' containment reference.
   * @see #setRegister(RegisterParam)
   * @see ceronsantiago.oneSharpExpressive.OneSharpExpressivePackage#getWrite_Register()
   * @model containment="true"
   * @generated
   */
  RegisterParam getRegister();

  /**
   * Sets the value of the '{@link ceronsantiago.oneSharpExpressive.Write#getRegister <em>Register</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Register</em>' containment reference.
   * @see #getRegister()
   * @generated
   */
  void setRegister(RegisterParam value);

  /**
   * Returns the value of the '<em><b>Word</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Word</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Word</em>' containment reference.
   * @see #setWord(WordParam)
   * @see ceronsantiago.oneSharpExpressive.OneSharpExpressivePackage#getWrite_Word()
   * @model containment="true"
   * @generated
   */
  WordParam getWord();

  /**
   * Sets the value of the '{@link ceronsantiago.oneSharpExpressive.Write#getWord <em>Word</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Word</em>' containment reference.
   * @see #getWord()
   * @generated
   */
  void setWord(WordParam value);

} // Write
