/**
 * generated by Xtext 2.9.0
 */
package ceronsantiago;

import ceronsantiago.AbstractOneSharpExpressiveRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class OneSharpExpressiveRuntimeModule extends AbstractOneSharpExpressiveRuntimeModule {
}
