/**
 * generated by Xtext 2.9.0
 */
package ceronsantiago.oneSharpExpressive.util;

import ceronsantiago.oneSharpExpressive.*;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.common.notify.impl.AdapterFactoryImpl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * The <b>Adapter Factory</b> for the model.
 * It provides an adapter <code>createXXX</code> method for each class of the model.
 * <!-- end-user-doc -->
 * @see ceronsantiago.oneSharpExpressive.OneSharpExpressivePackage
 * @generated
 */
public class OneSharpExpressiveAdapterFactory extends AdapterFactoryImpl
{
  /**
   * The cached model package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected static OneSharpExpressivePackage modelPackage;

  /**
   * Creates an instance of the adapter factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public OneSharpExpressiveAdapterFactory()
  {
    if (modelPackage == null)
    {
      modelPackage = OneSharpExpressivePackage.eINSTANCE;
    }
  }

  /**
   * Returns whether this factory is applicable for the type of the object.
   * <!-- begin-user-doc -->
   * This implementation returns <code>true</code> if the object is either the model's package or is an instance object of the model.
   * <!-- end-user-doc -->
   * @return whether this factory is applicable for the type of the object.
   * @generated
   */
  @Override
  public boolean isFactoryForType(Object object)
  {
    if (object == modelPackage)
    {
      return true;
    }
    if (object instanceof EObject)
    {
      return ((EObject)object).eClass().getEPackage() == modelPackage;
    }
    return false;
  }

  /**
   * The switch that delegates to the <code>createXXX</code> methods.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected OneSharpExpressiveSwitch<Adapter> modelSwitch =
    new OneSharpExpressiveSwitch<Adapter>()
    {
      @Override
      public Adapter caseProgram(Program object)
      {
        return createProgramAdapter();
      }
      @Override
      public Adapter caseRegisterParam(RegisterParam object)
      {
        return createRegisterParamAdapter();
      }
      @Override
      public Adapter caseWordParam(WordParam object)
      {
        return createWordParamAdapter();
      }
      @Override
      public Adapter caseCallParam(CallParam object)
      {
        return createCallParamAdapter();
      }
      @Override
      public Adapter caseWrite(Write object)
      {
        return createWriteAdapter();
      }
      @Override
      public Adapter caseNormalCase(NormalCase object)
      {
        return createNormalCaseAdapter();
      }
      @Override
      public Adapter caseGoto(Goto object)
      {
        return createGotoAdapter();
      }
      @Override
      public Adapter caseCall(Call object)
      {
        return createCallAdapter();
      }
      @Override
      public Adapter caseCommand(Command object)
      {
        return createCommandAdapter();
      }
      @Override
      public Adapter caseUnlabeledCommand(UnlabeledCommand object)
      {
        return createUnlabeledCommandAdapter();
      }
      @Override
      public Adapter caseIntParamDec(IntParamDec object)
      {
        return createIntParamDecAdapter();
      }
      @Override
      public Adapter caseStringParamDec(StringParamDec object)
      {
        return createStringParamDecAdapter();
      }
      @Override
      public Adapter caseParamDec(ParamDec object)
      {
        return createParamDecAdapter();
      }
      @Override
      public Adapter caseFunctionDeclaration(FunctionDeclaration object)
      {
        return createFunctionDeclarationAdapter();
      }
      @Override
      public Adapter caseCommandBlock(CommandBlock object)
      {
        return createCommandBlockAdapter();
      }
      @Override
      public Adapter defaultCase(EObject object)
      {
        return createEObjectAdapter();
      }
    };

  /**
   * Creates an adapter for the <code>target</code>.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param target the object to adapt.
   * @return the adapter for the <code>target</code>.
   * @generated
   */
  @Override
  public Adapter createAdapter(Notifier target)
  {
    return modelSwitch.doSwitch((EObject)target);
  }


  /**
   * Creates a new adapter for an object of class '{@link ceronsantiago.oneSharpExpressive.Program <em>Program</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see ceronsantiago.oneSharpExpressive.Program
   * @generated
   */
  public Adapter createProgramAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link ceronsantiago.oneSharpExpressive.RegisterParam <em>Register Param</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see ceronsantiago.oneSharpExpressive.RegisterParam
   * @generated
   */
  public Adapter createRegisterParamAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link ceronsantiago.oneSharpExpressive.WordParam <em>Word Param</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see ceronsantiago.oneSharpExpressive.WordParam
   * @generated
   */
  public Adapter createWordParamAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link ceronsantiago.oneSharpExpressive.CallParam <em>Call Param</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see ceronsantiago.oneSharpExpressive.CallParam
   * @generated
   */
  public Adapter createCallParamAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link ceronsantiago.oneSharpExpressive.Write <em>Write</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see ceronsantiago.oneSharpExpressive.Write
   * @generated
   */
  public Adapter createWriteAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link ceronsantiago.oneSharpExpressive.NormalCase <em>Normal Case</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see ceronsantiago.oneSharpExpressive.NormalCase
   * @generated
   */
  public Adapter createNormalCaseAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link ceronsantiago.oneSharpExpressive.Goto <em>Goto</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see ceronsantiago.oneSharpExpressive.Goto
   * @generated
   */
  public Adapter createGotoAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link ceronsantiago.oneSharpExpressive.Call <em>Call</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see ceronsantiago.oneSharpExpressive.Call
   * @generated
   */
  public Adapter createCallAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link ceronsantiago.oneSharpExpressive.Command <em>Command</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see ceronsantiago.oneSharpExpressive.Command
   * @generated
   */
  public Adapter createCommandAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link ceronsantiago.oneSharpExpressive.UnlabeledCommand <em>Unlabeled Command</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see ceronsantiago.oneSharpExpressive.UnlabeledCommand
   * @generated
   */
  public Adapter createUnlabeledCommandAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link ceronsantiago.oneSharpExpressive.IntParamDec <em>Int Param Dec</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see ceronsantiago.oneSharpExpressive.IntParamDec
   * @generated
   */
  public Adapter createIntParamDecAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link ceronsantiago.oneSharpExpressive.StringParamDec <em>String Param Dec</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see ceronsantiago.oneSharpExpressive.StringParamDec
   * @generated
   */
  public Adapter createStringParamDecAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link ceronsantiago.oneSharpExpressive.ParamDec <em>Param Dec</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see ceronsantiago.oneSharpExpressive.ParamDec
   * @generated
   */
  public Adapter createParamDecAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link ceronsantiago.oneSharpExpressive.FunctionDeclaration <em>Function Declaration</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see ceronsantiago.oneSharpExpressive.FunctionDeclaration
   * @generated
   */
  public Adapter createFunctionDeclarationAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link ceronsantiago.oneSharpExpressive.CommandBlock <em>Command Block</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see ceronsantiago.oneSharpExpressive.CommandBlock
   * @generated
   */
  public Adapter createCommandBlockAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for the default case.
   * <!-- begin-user-doc -->
   * This default implementation returns null.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @generated
   */
  public Adapter createEObjectAdapter()
  {
    return null;
  }

} //OneSharpExpressiveAdapterFactory
