/*
 * generated by Xtext 2.9.0
 */
package ceronsantiago


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class OneSharpExpressiveStandaloneSetup extends OneSharpExpressiveStandaloneSetupGenerated {

	def static void doSetup() {
		new OneSharpExpressiveStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
