/*
 * generated by Xtext 2.9.0
 */
package ceronsantiago.ui.tests;

import ceronsantiago.onesharpx.ui.internal.OnesharpxActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.junit4.IInjectorProvider;

public class OneSharpExpressiveUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return OnesharpxActivator.getInstance().getInjector("ceronsantiago.OneSharpExpressive");
	}

}
